version: '2'  
services:  
  o2r-bindings:
    build: ./
    ports:
     - "8092:8092"
     - "8000:8000"
    volumes: 
     - "./controllers/testdata:/controllers/testdata"
    environment: 
     - DEBUG=bindings